### ISSUE TITLE
[Suggestion] Resize log box

### ISSUE THREAD

**Issue by l0kt33n** [AnthonyOSX/GO-Bot#10]
Right now the log box only shows around five lines and resizing the window does not make the log box bigger.  Could we get the freedom to resize the layout on the GUI to have the log show more lines?

**Comment by MarcusOy** [comment]
Yeah, that would be a great idea.

**Comment by ilikesomething** [comment]
+1

**Comment by AnthonyOSX** [comment]
Will look into this, thanks.

**Comment by jodriscoll** [comment]
@l0kt33n +1

**Comment by MarcusOy** [comment]
On top of this suggestion, different event should be colored in different ways. Like catching Pokémon = green text, error = red text. @AnthonyOSX

**Comment by AnthonyOSX** [comment]
Updated in latest release.
