### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by kairotox** [AnthonyOSX/GO-Bot#101]
could not load file or assembly "google.Protobuf

**Comment by kairotox** [comment]
in 0.0.5

**Comment by azakhi** [comment]
Make sure there is a file named "Google.Protobuf.dll" in the same folder with the bot. If there is not, you can download one of previous releases and copy the file from there

**Comment by AnthonyOSX** [comment]
Download the latest release.

**Comment by kairotox** [comment]
Ah, didn't notice there was a new one, thank you sir!!!
