### ISSUE TITLE
v0.0.3 release still says v0.0.2 in the title bar

### ISSUE THREAD

**Issue by trcjr** [AnthonyOSX/GO-Bot#11]
v0.0.3 release still says v0.0.2 in the title bar

**Comment by CptJackieSparrow** [comment]
yeah i counter that too but there are files changed i think he forgot to rename it

**Comment by AnthonyOSX** [comment]
Will be fixed in next release.

**Comment by mstok444** [comment]
@AnthonyOSX Close

**Comment by AnthonyOSX** [comment]
Fixed.
