### ISSUE TITLE
0.5  error: account not verified exceptions

### ISSUE THREAD

**Issue by r4uschi** [AnthonyOSX/GO-Bot#113]
![error](https://cloud.githubusercontent.com/assets/20617201/17080200/a60e4966-5126-11e6-8f51-9d85ff2c5455.jpg)

**Comment by AnthonyOSX** [comment]
You need to confirm your email.

**Comment by r4uschi** [comment]
it works fine with 0.0.4 the error starts with 0.0.5 so i have no idea
