### ISSUE TITLE
Version .5 source not updated

### ISSUE THREAD

**Issue by jacksondog23** [AnthonyOSX/GO-Bot#118]
Doesn't look like it was committed or the source is correct in the release.

**Comment by AnthonyOSX** [comment]
Will be doing this later.

**Comment by jacksondog23** [comment]
Thanks!

**Comment by zgelici** [comment]
@AnthonyOSX when can we expect the update on the branch master

**Comment by TaylorZaneKirk** [comment]
Later... (TM)
