### ISSUE TITLE
Wrong Source Published for 0.0.5

### ISSUE THREAD

**Issue by dcmartinpc** [AnthonyOSX/GO-Bot#121]
I pulled down the source for 0.0.5 to make a few tweaks and it seems the source is for a previous version.  Could you please verify?

**Comment by jacksondog23** [comment]
He will updating it [later](https://github.com/AnthonyOSX/GO-Bot/issues/118#issuecomment-234742109)

**Comment by dcmartinpc** [comment]
Thank you.  I missed that post!
