### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by banan3k07** [AnthonyOSX/GO-Bot#122]
You should add pokestop farming ;) bot will leave pokemons and run only to pokestops.
Yes i also lost all pokeballs when i used ver. 0.0.5 :(

**Comment by boriss579** [comment]
This can cause a soft-ban very quickly from my experience.
Running for pokestops in other bots gave me soft-bans every time.
Maybe it is the fact that my area is low on pokestops and they quite far away from each other, but still this needs to be research more I think to prevent problems.

**Comment by AnthonyOSX** [comment]
It farms pokestops as well as pokemon.
