### ISSUE TITLE
V5 of bot

### ISSUE THREAD

**Issue by squishy23456** [AnthonyOSX/GO-Bot#123]
Just downloaded v5 and had some questions. Walking speed is set at 25km/hr? Is this too fast and will result in ban? 

Also the "delay between pokemon catch" is currently set at 5000. Is this in seconds? Since the bot is "walking" would it be reasonable to set it down close to 0?

Thanks!

**Comment by AnthonyOSX** [comment]
Walking speed is fine as is.

Delay between Pokemon catches is in millseconds. 5000 would be 5 seconds.
