### ISSUE TITLE
[Suggestion] Auto scroll checkbox

### ISSUE THREAD

**Issue by monachino** [AnthonyOSX/GO-Bot#124]
Would be handy to have the ability to stop the log from scrolling when you scroll up it, or when you check a checkbox.

Great work!

**Comment by TheHydride** [comment]
I was just thinking about this.

**Comment by AnthonyOSX** [comment]
Please view the README which describes where log files are stored. https://github.com/AnthonyOSX/GO-Bot/blob/master/README.md
