### ISSUE TITLE
0.4 vs 0.5

### ISSUE THREAD

**Issue by supermiguel** [AnthonyOSX/GO-Bot#126]
I see alot of issues with 0.5 few hours ago.. are those fixed? is 0.5 better than 0.4? or should i stay in .4?

**Comment by bowchicka777** [comment]
I'm getting a loop on "Requesting GetMapObjectsRespose" in v5 but its doing the same in v4

**Comment by rapublik** [comment]
soft-ban?

**Comment by bowchicka777** [comment]
just logged into the account on my phone and no soft ban, latitude and longitude is set at a spot 15 mins from home, and I waited 15 mins to log in

**Comment by cscsomers** [comment]
I've had better results with 0.4 so far, but I find 0.5 is better for hatching eggs and has more logic for evolving your Pokemon

**Comment by AnthonyOSX** [comment]
v0.0.5 is much better than v0.0.4. The only reason 4 might seem better is because it teleports from location to location while 5 has a walking algorithm.

**Comment by fenixasin** [comment]
do not go from 05 to 03  buddy  lost a maxed growlithe for some stupid reason it trans it
