### ISSUE TITLE
looping on "Requesting Getmapobjectsresponse" (V5)

### ISSUE THREAD

**Issue by bowchicka777** [AnthonyOSX/GO-Bot#129]
![fdsa](https://cloud.githubusercontent.com/assets/20618470/17080903/a91f7252-5107-11e6-81a9-49187b076424.PNG)

Created a PTC account, logged in on phone, put in name and caught a couple pokemon. 
put acct into bot (v5) and set coordinates for nearby university 15 mins away. waited 15 mins to start between phone and bot. Bot looped, so drove to get some lunch, logged into phone, caught pokemon so no soft ban, came back home. Still loops like above with no interactions. Not sure what I'm doing wrong.

**Comment by rapublik** [comment]
first log on bot 
phone gps turn off
after open on the phone,

**Comment by jodriscoll** [comment]
Do not log on to bot characters with your GPS turned on.

For IOS, go to Settings => Privacy => Location servers and turn it off before you log in.

Keep in mind, the GPS not found notification will block your settings button, not allowing you to log out in the App. You'll need to open the app, quickly click your Pokeball button, then click settings. Only then will you be able to log out of the character.

Hopefully that helps.

**Comment by bowchicka777** [comment]
okay so I opened up the account on my ipad with gps off while bot is running. Bot is still not interacting with anything.

Sorry if I wasn't clear, my problem is that the bot isn't interacting with anything and I'm not soft banned
. It's just showing the same information above over and over again without any actions.

**Comment by bowchicka777** [comment]
![fdsafdsa](https://cloud.githubusercontent.com/assets/20618470/17080966/8ead8c6c-510a-11e6-8744-5dfa8cfedc31.PNG)

**Comment by NamelessKaibutsu** [comment]
It works for me around 2 minutes and then I also get the same problem everytime

**Comment by bowchicka777** [comment]
On the bright side it does recycle items and transfer pokemon that I caught on the phone so that's working. 

Just created a fresh ptc account to try. Logged into phone first captured starter then logged out put info into bot at my exact coordinates. Still no actions outside of recycling items.

**Comment by AnthonyOSX** [comment]
Try a city lat/long or a place that has a lot of pokemon/pokestops.

**Comment by bowchicka777** [comment]
Did a lat/long in a city near me and now its doing work! Thank you so much!
