### ISSUE TITLE
We really need Google Sign In

### ISSUE THREAD

**Issue by Reitor** [AnthonyOSX/GO-Bot#133]

**Comment by jdspringr07** [comment]
Stop
Posting
Duplicate
Issues...

The following issues are requesting google access: #91, #85, #61, #133, #66, #61, #56, #7.

Please append a post to one of the already opened issues. You're just cluttering the issue tracker for no reason.

**Comment by fenixasin** [comment]
thanks jds, I have been too busy to help consolidate these issues
