### ISSUE TITLE
Older version on build with new source?

### ISSUE THREAD

**Issue by SparrowKane** [AnthonyOSX/GO-Bot#137]
I'm incredibly new to using VB and some of this is really confusing. I'm trying to use the source instead of the .exe, so that I can make some changes to personal preference on some of the functions. But when I try to build the project using either the 0.0.4 or 0.0.5 source, I end up with an old 0.0.2(Beta) client that doesn't include all of the new features on the configurations menu.  Is there something that I missed along the way?

**Comment by willshiao** [comment]
See #118.

**Comment by SparrowKane** [comment]
Oh, thank you!
