### ISSUE TITLE
Unable to find EXE

### ISSUE THREAD

**Issue by MeshaelR** [AnthonyOSX/GO-Bot#139]
Hello, I am somewhat new to working with git files, When I download the file as a zip, I am unable to find a .exe file, only sli files and cs. Any help would be appreciated. :)

**Comment by Wyn10** [comment]
https://github.com/AnthonyOSX/GO-Bot/releases/download/v0.0.5/GO.Bot.v0-0-5.zip

**Comment by MeshaelR** [comment]
Thanks!
