### ISSUE TITLE
Min IV Min Cp delay

### ISSUE THREAD

**Issue by Hrithikd** [AnthonyOSX/GO-Bot#141]
What is the delay measured in?
Also, for example, if the bot catches pidgeys and the transfer option is checked, will it keep the highest cp as well as any pidgeys that are over the min IV?

**Comment by VonSidia** [comment]
It will keep whatever duplicate pokemon your CP/IV or above is set to, so anything below it will transfer.

**Comment by Hrithikd** [comment]
oh but it will still keep the highest of that species even if that isnt above the min iv or min cp?

**Comment by VonSidia** [comment]
If you only have one of those types of pokemon it will keep it since it won't have any other duplicates.

**Comment by Hrithikd** [comment]
Is there any way to keep both the highest IV and the highest CP of that species?

**Comment by Hrithikd** [comment]
LOL i think im just gonna stick to version 3 as that will keep the highest cp

**Comment by VonSidia** [comment]
v3, 4 and 5 will all keep the highest CP but in v5 you will have duplicates of the above set CP/IV.

**Comment by AnthonyOSX** [comment]
Just set keep duplicates to 0?

**Comment by IsaacViThurston** [comment]
So if I just want to keep by IV then I just set CP to like 9999. But it should still keep anything above the IV I set right?

**Comment by Hrithikd** [comment]
@AnthonyOSX When i ran v5 it transferred my highest cp eevee for one that had a higher IV than the one i set
