### ISSUE TITLE
cant open exe

### ISSUE THREAD

**Issue by fendy123** [AnthonyOSX/GO-Bot#143]
hello
i used windows 10 64 bit..
i try download 0.5 and 0.4, but why i can't open the .exe files? 
when i 2clicked .exe nothing happens..

i already tried for donlod 4.5 net from microsoft and install it, but their said 
"Microsoft .NET Framework 4.5 is already a part of this operating system.  You do not need to install the .NET Framework 4.5 redistributable.
Same or higher version of .NET Framework 4.5 has already been installed on this computer."

what should i do now? please help.

**Comment by AnthonyOSX** [comment]
Right click -> run as administrator. If that doesn't work make sure your antivirus is disabled.

**Comment by fendy123** [comment]
still doesn't work.. already disable antivir and run as administrator
