### ISSUE TITLE
Log

### ISSUE THREAD

**Issue by TheReggaeSheep** [AnthonyOSX/GO-Bot#157]
it's next to impossible to try and read what the log said, a toggle for auto-scrolling would be appreciated. keep up the awesome work!!!

**Comment by KevinBassaDevelopment** [comment]
Maybe remove the "INFO Requesting XXX" from the log? 

It's not really interesting as it always occurs at the same position. 
And when the request fails we get an error message which will be displayed, so no information is lost.

**Comment by AnthonyOSX** [comment]
"C:\Users{Your username}\GO Bot\Logs\Output\output.txt"
