### ISSUE TITLE
Pokemon caught through the bots don't have a "Location" on their profile

### ISSUE THREAD

**Issue by sshum00** [AnthonyOSX/GO-Bot#160]
The "Location" part of the pokemon is empty for pokemons caught via the bot :(

**Comment by azakhi** [comment]
If you mean a blank box appearing as map that is not because of bot. Niantic probably disabled that feature to decrease server load

**Comment by KevinBassaDevelopment** [comment]
Yes, its now blank for all, I just checked. Seems it got temporary disabled.

**Comment by sshum00** [comment]
Ah, got it, thanks, closing the issue
