### ISSUE TITLE
Bot dont hatch eggs

### ISSUE THREAD

**Issue by Becold** [AnthonyOSX/GO-Bot#161]
Would be cool if the bot automatically hatch eggs

**Comment by IsaacViThurston** [comment]
It probably can if you set the max walk speed to 7km/hr or below. Right now it's moving as if your driving a car slowly around at 25km/hr which is over the limit for egg/distance tracking.

**Comment by TheMarxist** [comment]
That's odd. I've had mine set to the default speed of 25km/hr and it's been hatching eggs. You do have to manually add them to the incubator, but it should work for hatching them once you do that. 25kpm is 15.54mph, which is about the average biking speed and eggs semm to hatch for people riding bikes from what I've seen and from personal expirience playing.

**Comment by jodriscoll** [comment]
@Becold this has been requested, multiple times. Please don't create the same request over and over like people are doing with the Google Login request.

It will bombard the issue list and we're trying to keep this simple for @AnthonyOSX to track our requests...
