### ISSUE TITLE
Add Sort PokeStops by ShortestPath

### ISSUE THREAD

**Issue by KevinBassaDevelopment** [AnthonyOSX/GO-Bot#165]
When walking is implemented, the pokestops need to be sorted by the shortest path (dijkstra algorithm),
else it will take very long to walk 1000m etc.

**Comment by TheMarxist** [comment]
Why on earth would you be botting in a place that required you to travel 1000 meters to the nearest pokestop? I've never had it require me to walk more than 150 from one location to the next.

**Comment by AnthonyOSX** [comment]
A* would be a better approach since Dijkstra doesn't take into account the heuristic.

Not going to implement this though as this could be a tell to Niantic about who is cheating.
