### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by xskeeperx** [AnthonyOSX/GO-Bot#17]
This is all i get. Seems like it is failing to log in and is keeping retrying. Ideas?
greetings!

PS: its v 0.0.3 despite what the title line says!

![unbenannt](https://cloud.githubusercontent.com/assets/20583626/17040666/620286aa-4fa1-11e6-855b-ef782e8fa3db.PNG)

**Comment by humanstorm** [comment]
Pokemon server seem to be down at the moment. Just login with my Google Account.

**Comment by b0rn-tion** [comment]
google accounts dont work mines running smooth on a trainer account

**Comment by dgol1115** [comment]
so i'm getting the same thing, after attempting to change my coordinates. how do i restore to default coords/ autolocate?

**Comment by b0rn-tion** [comment]
put in cords with , instead of . if need be copy and paste from google maps guys

**Comment by dgol1115** [comment]
i understood that was 0.0.2, but i tried it and it left the issue the same.

**Comment by discordmaru** [comment]
I find if I open multiple accounts I have to use exact coords on each account or I get this error. Tested at 3 different locations.

**Comment by AnthonyOSX** [comment]
Servers were down, please try again.
