### ISSUE TITLE
Stupid Question, but give a try

### ISSUE THREAD

**Issue by zgelici** [AnthonyOSX/GO-Bot#178]
Hi,_ i try to build the executable by my self. but i get this error: 

![image](https://cloud.githubusercontent.com/assets/5995033/17084630/1db8799a-51c3-11e6-9169-fb5b96a184d4.png)

i use visual studio  2015.

Hope someone can help me?

**Comment by azakhi** [comment]
Expand References tab in the Solution Explorer and check if Google.Protobuff has any sign of warning on it (like a little yellow triangle). If so that means you didnt add it as reference

**Comment by zgelici** [comment]
Thanks, fixed it
