### ISSUE TITLE
Pokemon captured without location data

### ISSUE THREAD

**Issue by LJMProductions** [AnthonyOSX/GO-Bot#191]
The location data for captured Pokemon with this tool is blank.

**Comment by shadowsyllvet** [comment]
Isn't it blank for ALL pokemon? Using the official app all pokemon have that blank map in their stats page, if that's what your referring to.

**Comment by Foulwerp** [comment]
Ever since the three step bug, all maps have been blank.

**Comment by LJMProductions** [comment]
That is what I was referring to - didn't realize that it was an app bug.
I'll close this issue out - thanks for getting back to me
