### ISSUE TITLE
better place to start bot

### ISSUE THREAD

**Issue by armark1ng** [AnthonyOSX/GO-Bot#194]
i cant find any good location to get some nice pokemons can anyone suggest? thanks

**Comment by yudycb** [comment]
Central park, Santa Monica CA. Put www.pokevision.com and get the latitude and longitude.

**Comment by shadowsyllvet** [comment]
↑↑↑↑ This program catches pokemon around pokestops, the more pokestops you have in an area the more chances of finding pokemon. Finding a place where there are ALWAYS lures up will likely double your exp gain. depending on what your actual location is, look on reddit to find a place nearby that people are always talking about.

**Comment by fiorettijoe** [comment]
ComicCon, go there, bot happy.

**Comment by WambulanceDriver** [comment]
(Close issue, not bot related, general Pokémon go related)

**Comment by IsaacViThurston** [comment]
I've actually tested this in grand central park as well as a smaller city like seattle and other places. It seems to get about the same xp/hr and pokemon/hr no matter where I put it. Probably due to it's movement speed being so fast.

**Comment by AnthonyOSX** [comment]
Please keep this discussion in the Discord chat or Reddit :)
