### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by MOBSTERX** [AnthonyOSX/GO-Bot#2]
Why does it keep looping my login?

**Comment by AnthonyOSX** [comment]
Servers may be having problems. I'll look tomorrow to make sure it's not a bigger issue.

**Comment by Minkafighter** [comment]
Yup, looping login for me too.

**Comment by lgndz** [comment]
Im able to log via phone app but I am still looping in program

**Comment by spot88** [comment]
Got the same problem.

**Comment by AnthonyOSX** [comment]
Fixed in v0.0.2
