### ISSUE TITLE
Transfer problems

### ISSUE THREAD

**Issue by cwliias** [AnthonyOSX/GO-Bot#204]
I have my Keep IV min at 95
and my Keep Min CP at 1
And nothing seems be be being transferred.

Shouldn't that make it so just all 95%+ are kept no matter the cp and anything under 95% is transferred?

**Comment by Quttan** [comment]
I think you're using Min CP incorrectly. It will keep any pokemon with a CP higher than the number you set, so setting it at 1 will keep every pokemon you catch. I was confused about that option, too. It should probably have a clearer name, or some mouseover text that explains what it does.

**Comment by cwliias** [comment]
Yeah im wanting it to keep every pokemon over 1 cp and over 95% IVs

**Comment by tupeta** [comment]
Currently, the bot checks CP/IV separately, if either criteria is met it'll keep pokemon, so if you leave CP at 1 it'll keep all and won't transfer anything.

**Comment by cwliias** [comment]
will it then eventually check IV and transfer the lower IV's after a certain amount of time?

**Comment by Reazel** [comment]
Its an OR condition
So it keep the pokemon if it has enough CP or enough IV

CP 1000 IV 85
Keep all with CP > 1000 OR IV > 85
So it keeps a pokemon with 1001 CP and IV 10
it keeps 1 CP with 86 IV as well

**Comment by cwliias** [comment]
thank you for the clarification reazel! that's what i was coming to realize
