### ISSUE TITLE
Getting this when i hit start, seems to be stuck in a loop

### ISSUE THREAD

**Issue by Sumpner** [AnthonyOSX/GO-Bot#210]
http://imgur.com/a/PEgZV

That is the what i am getting, any ideas for a fix please?

By the way, keep up the good work guys!

**Comment by ricerocket** [comment]
i believe the PTC servers are down

**Comment by Sumpner** [comment]
Thanks Ricerocket, I thought that might be the case, as some friends can't make a new account.

**Comment by WambulanceDriver** [comment]
(closed) PTC server issue, not bot issue

**Comment by AnthonyOSX** [comment]
Servers are down.
