### ISSUE TITLE
Access Token Expired

### ISSUE THREAD

**Issue by LTracte** [AnthonyOSX/GO-Bot#212]
It wont log in anymore.  It says "Access Token Expired"

**Comment by Johaneto** [comment]
servers down I think [110](https://github.com/AnthonyOSX/GO-Bot/issues/110)

**Comment by RobbieK05** [comment]
Same for me, i was about to post an issue too

**Comment by LTracte** [comment]
server is not down.  i can log in with my regular account,  but the one i use the bot on wont sign in.

**Comment by strik3** [comment]
ptc servers are down

**Comment by LTracte** [comment]
i hope thats it

**Comment by strik3** [comment]
It's the only thing it can be. Tried logging in to the Orc with a spare account that has never been used and get authentication error on iOS and can't login with the bot. So pretty confident it's just the Servers down.

Plus ispokemongodwonornot is showing the Orc servers are offline

Sent from my iPhone

On 26 Jul 2016, at 12:01 AM, LTracte <notifications@github.com<mailto:notifications@github.com>> wrote:


i hope thats it

-

**Comment by UncleMart** [comment]
https://go.jooas.com

**Comment by yottabytez** [comment]
http://ispokemongodownornot.com/ 

It's the logins for PTC. I was watching when it went. It's not your accounts.

**Comment by WambulanceDriver** [comment]
(closed) PTC server issue, not bot related

**Comment by kaardilugeja** [comment]
F*ck, that's relieving ..

**Comment by fenixasin** [comment]
no kidding....  people are going to get to like lev 32 and  just put their bots away for a rainy day lol

I have a feeling the first few lev 40 accounts will be looked at closely

**Comment by Mod101** [comment]
funny, servers are down, but one my bots still running and grinding somehow... the other1 cant get on.

**Comment by Mod101** [comment]
and yes, u dont need more than level 30, as at 30 u get max cp as you would at level 40.

**Comment by AnthonyOSX** [comment]
Servers are down.

**Comment by TheReggaeSheep** [comment]
Just managed to get back in
