### ISSUE TITLE
Help Me! Plz :'c

### ISSUE THREAD

**Issue by HexicZ** [AnthonyOSX/GO-Bot#218]
I had a problem today when servers fell, the last 2 days the bot worked me correctly and today just when servers fell the program did not open me before worked me and told me about problems (because of the fallen servers) But nor do I now open, try reinstalling and not work...

I have Win10

**Comment by rayn21** [comment]
What do you mean by "did not open"? You click the application and it doesn't pop up?  Or you just are having trouble logging in?

**Comment by HexicZ** [comment]
I give open the .exe and does not open, I opened the task manager to see what happened, I gave the .exe and opened in managed tasks for a few moments and closed

**Comment by HexicZ** [comment]
Fixed!: I downgrade to Windows 7 :D
