### ISSUE TITLE
Can't login + no catching

### ISSUE THREAD

**Issue by iNordic** [AnthonyOSX/GO-Bot#24]
So first when i used it yesterday it worked and everything was good but today (first in v0.2) it wouldn't catch any pokemon. All of them would flee after the first ball, that also always failed, even on weak pokemons. If i go on bluestacks and do it from there i can also not capture any pokemons myself anymore. Is this some kind of soft-ban? Then i saw 0.3 was out and used that, and now on both 0.2 and 0.3 i doesn't log me in anymore and gives errors regarding a submodule which is the rocket api i think. Anyway if anyone knows fixes that would be gladly appreciated <3. Btw i already restarted multiple times yes.

**Comment by lgndz** [comment]
the servers are down

You can check this on multiple sites

Please use common sense. Close thjis issue please

**Comment by iNordic** [comment]
oh im so sorry. my other accounts were still working though so i thought it was something with this app
