### ISSUE TITLE
Format for coordinates? 

### ISSUE THREAD

**Issue by Nuggetfarm** [AnthonyOSX/GO-Bot#25]
It worked great untill I started messing with the coordinates. Whats the correct format? 

Im using google which looks something like this: 

53.2193835
6.566501799999969

**Comment by spot88** [comment]
Try with , not .

**Comment by Nuggetfarm** [comment]
tried it, doesnt work.

**Comment by Logis** [comment]
I can confirm it works with "." in version 0.0.3 (shows up as 0.0.2)

Creator fixed it in the 0.0.3 release
https://github.com/AnthonyOSX/GO-Bot/issues/8

**Comment by Nuggetfarm** [comment]
I fixed it changing the coordinates to , instead of .  

Thanks for the responses!
