### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by suhassamarth** [AnthonyOSX/GO-Bot#28]
![error](https://cloud.githubusercontent.com/assets/20596733/17056908/5fd07d18-5034-11e6-84d3-e29cbef5bc10.png)

**Comment by suhassamarth** [comment]
Help me with this pls

**Comment by azakhi** [comment]
PTC Servers are down atm that is probably the reason

**Comment by mstok444** [comment]
Have seen this a few times, seems to relate to moving into water. Try a different set of coordinates.

**Comment by AnthonyOSX** [comment]
Fixed in latest release.
