### ISSUE TITLE
Every single pokemon runs away.

### ISSUE THREAD

**Issue by RZeroFrost** [AnthonyOSX/GO-Bot#3]
http://imgur.com/a/hglrQ

Image basically shows the issue,
I do have 100+ pokeballs, not sure whats wrong with it.
It worked fine for the first few minutes.

**Comment by AnthonyOSX** [comment]
You may have been soft banned by Niantic. Try again in a few hours.

**Comment by RZeroFrost** [comment]
I think I figured it out, basically when you try to shut down the app, the cef.sharp browser s.proc. doesnt close. So, if the user immediately restarts it, then it bugs out and essentially tries to tunnel multiple locations and the server doesnt know what to send back.
