### ISSUE TITLE
Wrong file in zip folder

### ISSUE THREAD

**Issue by c5vette211** [AnthonyOSX/GO-Bot#31]
The zip and DL says 0.0.3 and the .exe is 0.0.2

![image](https://cloud.githubusercontent.com/assets/19394345/17059877/4791e21c-4ff5-11e6-9b88-a1b803265c89.png)

**Comment by Logis** [comment]
Know issue

https://github.com/AnthonyOSX/GO-Bot/issues/11

**Comment by c5vette211** [comment]
I think because of this it is causing infinite login loop. It was said in a previous post that it was due to servers being down. Servers are back up and still getting infinite login.

**Comment by azakhi** [comment]
Im using 0.0.3 and it is working great atm

**Comment by c5vette211** [comment]
i was using 3 on a different computer last night. I downloaded the zip for 3 this morning and it contained 2. so currently I am not sure how to DL 3 since the wrong file is in the 3 zip

**Comment by MreinstienZ** [comment]
i get the unlimited login loop, the PTC servers are online though i dont know what to do can someone help me pls

**Comment by Maccawelsh** [comment]
I cant seem to find the exec file pleas help

**Comment by MreinstienZ** [comment]
https://github.com/AnthonyOSX/GO-Bot/releases go here and download release has exec in it

**Comment by mstok444** [comment]
The wrong file is not in the 3 zip, he just forgot to change the name, its been changed for the next release.

**Comment by jdspringr07** [comment]
Please close this issue. This has been marked like 3 times already.

**Comment by AnthonyOSX** [comment]
Fixed in v0.0.4
