### ISSUE TITLE
NullReferenceException: d_0.MoveNext() 

### ISSUE THREAD

**Issue by Mineroboter** [AnthonyOSX/GO-Bot#33]
When I start the Bot this happens: (German)
![1](https://cloud.githubusercontent.com/assets/13052748/17061457/dc896b18-502e-11e6-98d7-46986d371672.PNG)
![2](https://cloud.githubusercontent.com/assets/13052748/17061456/dc86cd72-502e-11e6-9351-bd7137361f81.PNG)
![3](https://cloud.githubusercontent.com/assets/13052748/17061458/dc8b6440-502e-11e6-870a-f2ed87ff1ce2.PNG)
And then it repeat all from "Setting up..." over and over again.
I think this happens because there are no pokemon near me.
I also changed the position but that shouldn't affect the bot.

**Comment by mstok444** [comment]
Some positions seem to parse incorrectly, I've mainly seen issues with the bot travelling into water. Nonetheless, try new coordinates and you should see improvement.

**Comment by Mineroboter** [comment]
I forgot to login normal in the app and create the charakter. I'm using for my main account Google.
But I have now this error: #43
And my credentials are correct.
