### ISSUE TITLE
Constant login loop v 3 

### ISSUE THREAD

**Issue by Maccawelsh** [AnthonyOSX/GO-Bot#34]
I currently am using the 3rd version of the standalone version and it just does a login loop. Any fixes would be appreciated.
![image](https://cloud.githubusercontent.com/assets/20584520/17063447/36f3fc8a-502f-11e6-841a-7947173b1d95.png)

**Comment by mstok444** [comment]
Make sure your Lat/Long, if you changed them are 6 digits after the decimal.
Also check your local server status as the bot doesnt always catch a failed server request.

**Comment by Maccawelsh** [comment]
I copied and pasted off google maps but it is only 5 after decimal.

**Comment by Maccawelsh** [comment]
I copied and pasted of the gmaps and it gave me 5 so I just changed it and it fixed thanks for the help

**Comment by Maccawelsh** [comment]
I just changed it and it still does the login loop usually after transferring  pokemon.

**Comment by Becold** [comment]
Use , instead of .

Here is an example: https://puu.sh/qaEVX/e416f91a7e.png

**Comment by Maccawelsh** [comment]
It wont let me put in the commas

**Comment by mstok444** [comment]
It "wont let you", elaborate please. Should be as simple as replacing the decimals with a comma in the lat/long input boxes.

**Comment by ftonk** [comment]
I've put in commas, still doesnt work and I get the same loop.

http://i.imgur.com/JO6n4Yh.png

**Comment by eherranzr** [comment]
Same problem here
![captura](https://cloud.githubusercontent.com/assets/20601242/17064418/ac86b6e2-503c-11e6-8388-eb09f40c525c.PNG)

**Comment by Maccawelsh** [comment]
It seems to be working with the decimals but it will not let me input the comma without deleting the comma from the lat/long. I also tried putting it in Santa Monica pier and this works but for how long I don't know.

**Comment by Maccawelsh** [comment]
eherranzr I recommend  you dont't launch the game with the ptc account and you can go anywhere in the world as long as you dont launch the app and you think the time it took to get to the place e.g. Santa Monica Pier for me and it will probably take 1 day to get from there to where I live so I would wait a day to launch the account from my house.

**Comment by eherranzr** [comment]
I'm just entering now the coordinates where I live to try but they don't work, and I don't know why. It may be because of this?
![captura](https://cloud.githubusercontent.com/assets/20601242/17064689/1fbb92da-503e-11e6-817c-97d7d46baf6e.PNG)

**Comment by Maccawelsh** [comment]
is that on your actual pc or the exec? Your pc long/lat does not change the exec so if you make a new ptc account and enter these into the configuration tab on the exec 
![image](https://cloud.githubusercontent.com/assets/20584520/17064795/4ca83a9e-5036-11e6-90aa-83a07cae5170.png)

**Comment by eherranzr** [comment]
It's my pc but maybe it's the problem the way the computer uses decimal separators. It's in control panel, Region>Aditional configuration

**Comment by Maccawelsh** [comment]
I didn't change anything with my computer and mine also uses decimals separators. I would also like to see your settings in english as I cant help if it is in spanish (Not meant to be read in a dicky way just want to help you)

**Comment by eherranzr** [comment]
I've just created a new account and entered your coordinates and it worked well.
I've also realised that your coordinates have 7 decimals instead of 6. May that be the problem?

**Comment by ftonk** [comment]
Worked for me when I used Maccawelsh coords, not the ones that I've used for central park. Hmm..

**Comment by ftonk** [comment]
And I used an old account

**Comment by Maccawelsh** [comment]
Ok guys don't go straight to your house wait a day with the bot closed to do so or you will be banned by the algorithm

**Comment by Maccawelsh** [comment]
Also, if you use a bran new account it will not transfer the Pokemon until the end when it will transfer the lowest lvl. I think it may not work in our locations eherranzr due to the lack of poke-stops or bad server response

**Comment by eherranzr** [comment]
I'll leave my 1st account (the old) untouched until tomorrow and I'll try to start the bot again tomorrow with that account to check.
Now, I'm using the bot with the new account and it farms correctly with your coordinates

**Comment by Maccawelsh** [comment]
Guys go on my post called Suggestion and type suggestions to improve the app and hope anthony sees it

**Comment by Maccawelsh** [comment]
Once your backpack fills up on items I reccomend doing this
I been working around that by using blue stacks. I can log onto the account at same locations at the same time without logging off bot . I clean my stash of all the potions and berries. It's a temp solution till it may be implemented. I only need to do it about every 7 hours or after the first cleaning.

**Comment by ftonk** [comment]
Ive noticed that I can turn my gps off, stop the cheat and go into the app and remove the stuff I dont need. And start the cheat again, works perfectly

**Comment by Maccawelsh** [comment]
Ahh ty much better way

**Comment by eherranzr** [comment]
How do you fake location in bluestacks? It doesn't seem to work for me

**Comment by ftonk** [comment]
Get lucky patcher and FakeGPS

**Comment by Maccawelsh** [comment]
ftonk I just launched my game first time on my s5 and it doesnt let me capture my starters

**Comment by Maccawelsh** [comment]
So I am trying it with bluestacks instead

**Comment by c5vette211** [comment]
can you elaborate on this:

"Ok guys don't go straight to your house wait a day with the bot closed to do so or you will be banned by the algorithm"

**Comment by eherranzr** [comment]
If you change quickly your location by huge distances eg. from EEUU to France in 10 minutes, tou'll be banned. Wait enough time so you could travel that distance in real life.

BTW, how could I disable location in Bluestacks using FakeGPS? I tried with the stop button in FakeGPS but PoGo stills locate me

**Comment by Maccawelsh** [comment]
eherranzr use a program called nox it is much better you dont need to install any other programs. That is tut

https://www.youtube.com/watch?v=iEvzi2jelfk

**Comment by eherranzr** [comment]
I've read about it but I'm too lazy to change the program now that I have Bluestacks working. Thanks anyway!

**Comment by Maccawelsh** [comment]
Btw the servers are down so gl getting on

**Comment by Maccawelsh** [comment]
well the ptc servers are down but google is fine

**Comment by Maccawelsh** [comment]
Severs back up but going take a long time to load
