### ISSUE TITLE
Exception after login

### ISSUE THREAD

**Issue by raidcookie** [AnthonyOSX/GO-Bot#43]
![ss 2016-07-22 at 07 30 07](https://cloud.githubusercontent.com/assets/5206862/17065674/757e0e00-5043-11e6-9b36-18bdec27f546.png)

This is what I'm getting every time I want to use the bot. I've tried it on my work laptop, which is running Windows 8.1 and it worked fine. My desktop is on Win7, and every time I try to log in through the bot I get this exception thrown at me. 

I've also tried other people's solutions such as replacing the period in the GPS coordinates with a comma, and trying to log in on a fresh account to no avail.

**Comment by MessiahMK** [comment]
Its a failed login attempt. I got it when I misspelled a password.

**Comment by Mineroboter** [comment]
What username should I use for login? The username of the PTC or the Pokemon GO charakter

**Comment by MessiahMK** [comment]
Username of PTC

**Comment by manniL** [comment]
Looks like the servers can't be accessed. wrong credentials or unstable login server for PTC

**Comment by raidcookie** [comment]
Turns out my PTC account was locked for too many failed login attempts. Thanks anyway!
