### ISSUE TITLE
Unexpected character encountered while parsing value

### ISSUE THREAD

**Issue by l0lpb** [AnthonyOSX/GO-Bot#50]
Game was working just fine but some reason around 11:30 it crashed and dont seem to get out of it.
the pokemon go work perfect on Nox and Bluestacks,  during this time so it shoulden't be the go server

[output.txt](https://github.com/AnthonyOSX/GO-Bot/files/379156/output.txt)
[error.txt](https://github.com/AnthonyOSX/GO-Bot/files/379157/error.txt)

**Comment by jdspringr07** [comment]
The ptc servers are still flakey. Have been for hours now. You do kno the google auth and ptc auth are two seperate items?

**Comment by l0lpb** [comment]
i expect that but both was PTC. anyway you seem correct it disapeared. sorry to have botherd you

**Comment by jdspringr07** [comment]
Are tou able to close this issue since u are the author?
