### ISSUE TITLE
how do i run it

### ISSUE THREAD

**Issue by Jeziell** [AnthonyOSX/GO-Bot#51]
i dont have any exe file on the folder, do i need to modify something?

**Comment by tazzcom** [comment]
Make sure you downloaded the Go-Bot.zip file and not the source ones,. Then after you unzip it just click on the GO Bot.exe and enter in your PTC info. https://github.com/AnthonyOSX/GO-Bot/releases/tag/v0.0.3

**Comment by squishy23456** [comment]
Sorry for the noob question but do you not need an emulator? You just run exe and it auto farms without you seeing any visuals? Thnx

**Comment by pmobes** [comment]
@squishy23456 that is correct.

**Comment by Jeziell** [comment]
Oh, I downloaded the source one I think, thank you.

El jul. 22, 2016 5:59 PM, tazzcom <notifications@github.com> escribió:

Make sure you downloaded the Go-Bot.zip file and not the source ones,. Then after you unzip it just click on the GO Bot.exe and enter in your PTC info. https://github.com/AnthonyOSX/GO-Bot/releases/tag/v0.0.3

**Comment by jdspringr07** [comment]
You have to download from the releases tab, not the source. Please close this issue when u get a chance.
