### ISSUE TITLE
Noob question, cannot run the bot

### ISSUE THREAD

**Issue by cluo40** [AnthonyOSX/GO-Bot#52]
Hi all, 

After I enter in my PTC info, it goes

setting up
beginning to farm...
starting execute on login server. Ptc
ERROR | System.NullReferenceException: Object reference not set to an instance of an object 

and more errors

![image](https://cloud.githubusercontent.com/assets/20605353/17073725/716e85c6-5041-11e6-9d45-2ab5170c5cc5.png)

It just keeps repeating this. 

Any help is much appreciated :)

**Comment by pmobes** [comment]
this is likely just an issue with the terrible PTC login server being down. you can try to use only 6-digits after the decimal point in your coords, and/or changing the decimal points to commas in your coords. if neither of those work, it's probably an issue with the PTC login server.

**Comment by jdspringr07** [comment]
This error wqs due to authentication issues with ptc. Ptc and google auth servers are seperate. Please close this issue.
