### ISSUE TITLE
Everytime I download sourcecode, Pokemon Go Api folder seems to be empty. Generates several errors when opening solution in VS2015 Pro.

### ISSUE THREAD

**Issue by MarcusOy** [AnthonyOSX/GO-Bot#6]
I'm sorta new to Github, but there is a different icon for the folder on the Github page. Does that mean that that folder is empty when source code is downloaded?

Also, just a heads up to the dev, I get several errors when opening up the solution due to broken references to NLog and Newtonsoft.JSON. To fix these errors, open the NuGet package manager and restore missing packages.

![image](https://cloud.githubusercontent.com/assets/16263577/17032874/538f73e2-4f30-11e6-8a86-c024b3f655c4.png)

**Comment by AnthonyOSX** [comment]
Go to releases tab -> download the latest release -> unzip -> run "GO Bot.exe".

There is no need for Visual Studio as I've created release builds.

**Comment by MarcusOy** [comment]
I am running your latest release right now, but i was just poking through the code, just trying to see whats going on.
