### ISSUE TITLE
lat/long fields in configuration do not allow decimal point to be entered

### ISSUE THREAD

**Issue by M230** [AnthonyOSX/GO-Bot#8]
Only numbers are allowed

**Comment by AnthonyOSX** [comment]
Will fix in next release, thanks for letting me know!

**Comment by trcjr** [comment]
Same thing for negative numbers, I couldn't enter a '-'.

**Comment by AnthonyOSX** [comment]
Fixed in v0.0.3. Please download from the releases tab.
