### ISSUE TITLE
The .exe doesn't load.

### ISSUE THREAD

**Issue by Mxnny** [AnthonyOSX/GO-Bot#86]
I'm having an issue with actually getting the program to load up, I've tried running it normally and as administrator and no matter how much times I click it nothing comes up on the screen if you know what I mean, what am I doing wrong?

**Comment by AnthonyOSX** [comment]
Do you have .NET 4.5 installed?

**Comment by Mxnny** [comment]
Thanks so much, sorry I'm not that good with computer stuff, thanks again :)
