### ISSUE TITLE
Possible Perma-ban?

### ISSUE THREAD

**Issue by arr0wed** [AnthonyOSX/GO-Bot#87]
Perhaps someone with a solid understanding of Pokemon GO bans can give me some advice..

I understand that soft bans should last anywhere from 5 minutes to 2 hours. My issue is that around 5 hours ago I attempted to move to a new location, "maybe" 2 miles from where I was before. I waited about 10 minutes before doing this. At this new location I was getting the typical 0XP and no catches that come with a soft ban. I waited 45 minutes and tried again, but I was still getting no XP and no catches. I waited an hour and tried to go back to my previous location, but still saw the same soft-ban response.

I tried a different GUI to see if something had happened with this one, but no improvement.

I waited a full 2 hours, and tried connecting to that same location on this GUI (no change in the coordinates), and still nothing.

I have no problem logging in to the account on my phone, with the GPS disabled. Because my usual farming location is somewhat far from my house, I never enable GPS when I check my account on my phone. Thus, I can't say whether the account will work on my phone if I activated GPS.

If you have experienced something like this _and/or_ know of a solution, please help a sister out.

**Comment by Sharpienero** [comment]
Not a bug.

**Comment by arr0wed** [comment]
Well, ok then. If anyone has any **advice or solutions** I would greatly appreciate the assistance.

**Comment by discordmaru** [comment]
Can last up to 12 hours

**Comment by alucard0134** [comment]
@Sharpienero Please don't contribute with useless comments, even if its just asking for advice.

@arr0wed A soft ban is pretty random tbh, they can only be 15 minutes, but then can go up to 12 hours. Just wait a day and see

**Comment by jdspringr07** [comment]
This is not a forum for diacusoing bans, asking questions, or advice lol. This is for reporting actual issues in the bot itself.

No one here has any clue on what kind of behavior Niantic scans for or what their punishments may be..

**Comment by AnthonyOSX** [comment]
Wait at least a day, then you should be good. If you'd like to discuss this further please make a post on Reddit.
