### ISSUE TITLE
Cant stop The bot... Ant suggest?

### ISSUE THREAD

**Issue by yudycb** [AnthonyOSX/GO-Bot#90]

**Comment by Sharpienero** [comment]
You've added zero details.

**Comment by alucard0134** [comment]
You can just close it and re open it.

**Comment by jdspringr07** [comment]
Download v0.0.4 and try. Elsewise you can exit. Also, please close this issue..  there are other issues with the same request.

**Comment by AnthonyOSX** [comment]
Close and re open the bot for now.
