### ISSUE TITLE
Long and Lat not changing in ver 5

### ISSUE THREAD

**Issue by TheHydride** [AnthonyOSX/GO-Bot#92]
First off, props to you for adding the new features us leechers were wanting. 

Second, even though I changed the lat and long, the bot still loads with the default numbers.

**Comment by kairotox** [comment]
Verified.

**Comment by oho911** [comment]
@kairotox @AnthonyOSX may i know what the funtion off altitude ??

**Comment by kairotox** [comment]
34.009477 -118.496801 is what I put in,  Lat: 39.986855 Lng: -75.196442 is what's showing up in the log.

It appears as though it's going off of the coords txt, and not the in-app modifier.

**Comment by NamelessKaibutsu** [comment]
same problem

**Comment by AnthonyOSX** [comment]
Fixed, please redownload.
